enum eGameSetting : uint32_t {
    sMusicVolume = 0; // slider
    sSoundVolume = 1; // slider
    sGamma = 2;
    sDifficulty = 3;
    sGameSensitivity = 4;
    sInterfaceSensitivity = 5;
    bViewBobbing = 6;
    Unknown7 = 7;
    bInvertLook = 8;
    bSouthpaw = 9;
    UnknownA = 10;
    bVerticalSplitscreen = 11;
    bInGameGamertags = 12;
    sAutosaveTimer = 13;
    bSplitscreenGamertags = 14;
    bHints = 15;
    sInterfaceOpacity = 16;
    bInGameTooltips = 17;
    bRenderClouds = 18;
    Unknown16 = 22;
    bDisplayHud = 23;
    bDisplayHand = 24;
    bCustomSkinAnimation = 25;
    bDeathMessages = 26;
    sHudSize = 27;
    sHudSizeSplitscreen = 28;
    bAnimatedCharacter = 29;
    bClassicCrafting = 32;
    bCaveSounds = 33;
    bGameChat = 34;
    bMinecartSounds = 35;
    Unknown24 = 36;
    Unknown25 = 37;
    bDisplayGameMessages = 38;
    bDisplaySaveIcon = 39; // (probably)
    rbFlyingViewRolling = 40;
    bShowGlideGhost = 42;
    bShowGlideGhostPath = 43;
    bAutoJump = 44;
    Unknown = 45;
} // Names are not original. (s = slider, b = bool, r = inverse)