#include "Minecraft/Classes/C4JThread.h"
#include "Other/Headers/winnt.h/LPCSTR.h"
#include "Other/Headers/winnt.h/HANDLE.h"
struct C4JThreadImpl : public C4JThread {
    undefined8 field_8;
    undefined8 field_16;
    int field_24;
    LPCSTR threadName;
    undefined field_36;
    undefined field_37;
    undefined field_38;
    undefined field_39;
    undefined field_40;
    undefined field_41;
    undefined field_42;
    undefined field_43;
    undefined field_44;
    undefined field_45;
    undefined field_46;
    undefined field_47;
    undefined field_48;
    undefined field_49;
    undefined field_50;
    undefined field_51;
    undefined field_52;
    undefined field_53;
    undefined field_54;
    undefined field_55;
    undefined field_56;
    undefined field_57;
    undefined field_58;
    undefined field_59;
    undefined field_60;
    undefined field_61;
    undefined field_62;
    undefined field_63;
    undefined field_64;
    undefined field_65;
    undefined field_66;
    undefined field_67;
    undefined field_68;
    undefined field_69;
    undefined field_70;
    undefined field_71;
    undefined field_72;
    undefined field_73;
    undefined field_74;
    undefined field_75;
    undefined field_76;
    undefined field_77;
    undefined field_78;
    undefined field_79;
    undefined field_80;
    undefined field_81;
    undefined field_82;
    undefined field_83;
    undefined field_84;
    undefined field_85;
    undefined field_86;
    undefined field_87;
    undefined field_88;
    undefined field_89;
    undefined field_90;
    undefined field_91;
    undefined1 processor; // Created by retype action
    undefined field_93;
    undefined field_94;
    undefined field_95;
    bool running; // Created by retype action
    bool started;
    undefined field_98;
    undefined field_99;
    undefined4 field_100;
    ulonglong startTime; // Created by retype action
    bool deleteOnExit; // Created by retype action
    undefined field_113;
    undefined field_114;
    undefined field_115;
    undefined field_116;
    undefined field_117;
    undefined field_118;
    undefined field_119;
    undefined8 field_120;
    undefined4 field_128;
    undefined field_132;
    undefined field_133;
    undefined field_134;
    undefined field_135;
    HANDLE thread;
} // PlaceHolder Class Structure