#include "Minecraft/Classes/ConsoleInputSource.h"
#include "Minecraft/Classes/Settings.h"
#include "Minecraft/Classes/Level.h"
#include "Minecraft/Classes/ConsoleSchematicFile.h"
#include "Minecraft/Classes/FillTool.h"
#include "Minecraft/Classes/Random.h"
#include "Minecraft/Classes/std/basic_string%3Cwchar_t%3E.h"
struct MinecraftServer : public ConsoleInputSource {
    undefined8 field_8;
    Settings * settings;
    Level * * field_24;
    undefined4 field_32;
    undefined field_36;
    undefined field_37;
    undefined field_38;
    undefined field_39;
    Settings * players;
    ConsoleSchematicFile * schematicFile;
    FillTool * fillTool;
    Random random;
    undefined field_73;
    undefined field_74;
    undefined field_75;
    undefined field_76;
    undefined field_77;
    undefined field_78;
    undefined field_79;
    undefined field_80;
    undefined field_81;
    undefined field_82;
    undefined field_83;
    undefined field_84;
    undefined field_85;
    undefined field_86;
    undefined field_87;
    Settings * field_88;
    undefined2 field_96;
    undefined1 field_98;
    undefined field_99;
    undefined4 field_100;
    undefined2 * field_104;
    undefined field_112;
    undefined field_113;
    undefined field_114;
    undefined field_115;
    undefined field_116;
    undefined field_117;
    undefined field_118;
    undefined field_119;
    Level * * field_120;
    ulonglong field_128;
    undefined4 field_136;
    undefined field_140;
    undefined field_141;
    undefined field_142;
    undefined field_143;
    FillTool * field_144;
    undefined8 field_152;
    Settings * field_160;
    Level * * field_168;
    undefined field_176;
    undefined field_177;
    undefined field_178;
    undefined field_179;
    undefined field_180;
    undefined field_181;
    undefined field_182;
    undefined field_183;
    basic_string<wchar_t> field_184;
    Level * * field_216;
    undefined1 field_224;
    undefined field_225;
    undefined field_226;
    undefined field_227;
    undefined field_228;
    undefined field_229;
    undefined field_230;
    undefined field_231;
    Settings * field_232;
    void * * field_240;
    undefined8 field_248;
    undefined field_256;
    undefined field_257;
    undefined field_258;
    undefined field_259;
    undefined field_260;
    undefined field_261;
    undefined field_262;
    undefined field_263;
    Level * * field_264;
    undefined8 field_272;
    Settings * field_280;
    undefined field_288;
    undefined field_289;
    undefined field_290;
    undefined field_291;
    undefined field_292;
    undefined field_293;
    undefined field_294;
    undefined field_295;
    undefined field_296;
    undefined field_297;
    undefined field_298;
    undefined field_299;
    undefined field_300;
    undefined field_301;
    undefined field_302;
    undefined field_303;
    undefined field_304;
    undefined field_305;
    undefined field_306;
    undefined field_307;
    undefined field_308;
    undefined field_309;
    undefined field_310;
    undefined field_311;
    undefined field_312;
    undefined field_313;
    undefined field_314;
    undefined field_315;
    undefined field_316;
    undefined field_317;
    undefined field_318;
    undefined field_319;
    undefined field_320;
    undefined field_321;
    undefined field_322;
    undefined field_323;
    undefined field_324;
    undefined field_325;
    undefined field_326;
    undefined field_327;
    Settings * field_328;
    undefined1 field_336;
    undefined field_337;
    undefined field_338;
    undefined field_339;
    undefined field_340;
    undefined field_341;
    undefined field_342;
    undefined field_343;
    undefined8 field_344;
    undefined2 field_352;
} // PlaceHolder Class Structure