#include "Minecraft/Classes/std/basic_string%3Cwchar_t%3E.h"
#include "Minecraft/Classes/Model.h"
struct ModelPart {
    void * * vftable;
    float xTexSize;
    float yTexSize;
    float x;
    float y;
    float z;
    float field_28;
    undefined8 field_32;
    float xRot;
    float yRot;
    float zRot;
    undefined2 field_52;
    undefined1 field_54;
    undefined field_55;
    undefined8 field_56;
    undefined8 field_64;
    undefined8 field_72;
    undefined8 field_80;
    undefined8 field_88;
    undefined8 field_96;
    undefined4 field_104;
    undefined8 field_108;
    undefined8 field_116;
    float field_124;
    float field_128;
    undefined8 field_132;
    undefined field_140;
    undefined field_141;
    undefined field_142;
    undefined field_143;
    basic_string<wchar_t> * id;
    undefined field_152;
    undefined field_153;
    undefined field_154;
    undefined field_155;
    undefined field_156;
    undefined field_157;
    undefined field_158;
    undefined field_159;
    ulonglong field_160;
    ulonglong field_168;
    int field_176;
    int field_180;
    undefined1 field_184;
    undefined field_185;
    undefined field_186;
    undefined field_187;
    undefined4 field_188;
    Model * model;
    float field_200;
    undefined1 field_204;
    undefined field_205;
    undefined field_206;
    undefined field_207;
}