#include "Minecraft/Classes/std/std%3A%3Abasic_string%3Cwchar_t%3E.h"
#include "Minecraft/Classes/Item%3A%3ATier.h"
struct SwordItem {
    undefined * * vftable;
    undefined field_8;
    undefined field_9;
    undefined field_10;
    undefined field_11;
    undefined field_12;
    undefined field_13;
    undefined field_14;
    undefined field_15;
    longlong * field_16;
    undefined4 field_24;
    int field_28;
    undefined8 field_32;
    undefined8 field_40;
    undefined2 field_48;
    undefined field_50;
    undefined field_51;
    undefined field_52;
    undefined field_53;
    undefined field_54;
    undefined field_55;
    undefined8 field_56;
    std::basic_string<wchar_t> field_64;
    undefined field_96;
    undefined field_97;
    undefined field_98;
    undefined field_99;
    undefined field_100;
    undefined field_101;
    undefined field_102;
    undefined field_103;
    std::basic_string<wchar_t> * field_104;
    undefined field_112;
    undefined field_113;
    undefined field_114;
    undefined field_115;
    undefined field_116;
    undefined field_117;
    undefined field_118;
    undefined field_119;
    ulonglong field_120;
    ulonglong field_128;
    undefined field_136;
    undefined field_137;
    undefined field_138;
    undefined field_139;
    undefined field_140;
    undefined field_141;
    undefined field_142;
    undefined field_143;
    undefined4 field_144;
    undefined field_148;
    undefined field_149;
    undefined field_150;
    undefined field_151;
    Item::Tier * tier;
} // PlaceHolder Class Structure