
struct UIControl {
    undefined * * vftable;
    undefined4 field_8;
    undefined field_12;
    undefined field_13;
    undefined field_14;
    undefined field_15;
    undefined field_16;
    undefined field_17;
    undefined field_18;
    undefined field_19;
    undefined field_20;
    undefined field_21;
    undefined field_22;
    undefined field_23;
    undefined8 * field_24;
    undefined field_32;
    undefined field_33;
    undefined field_34;
    undefined field_35;
    undefined field_36;
    undefined field_37;
    undefined field_38;
    undefined field_39;
    undefined8 field_40;
    ulonglong field_48;
    undefined8 field_56;
    undefined8 field_64;
    undefined field_72;
    undefined field_73;
    undefined field_74;
    undefined field_75;
    undefined field_76;
    undefined field_77;
    undefined field_78;
    undefined field_79;
    undefined field_80;
    undefined field_81;
    undefined field_82;
    undefined field_83;
    undefined field_84;
    undefined field_85;
    undefined field_86;
    undefined field_87;
    undefined4 field_88;
    undefined field_92;
} // PlaceHolder Class Structure