#include "Minecraft/Classes/FUI/RenderNode/fuiRenderNode.h"
struct FJ_FuiNode {
    void * * vftable;
    fuiRenderNode * node;
    undefined field_16;
    undefined field_17;
    undefined field_18;
    undefined field_19;
    undefined field_20;
    undefined field_21;
    undefined field_22;
    undefined field_23;
    undefined field_24;
    undefined field_25;
    undefined field_26;
    undefined field_27;
    undefined field_28;
    undefined field_29;
    undefined field_30;
    undefined field_31;
    undefined field_32;
    undefined field_33;
    undefined field_34;
    undefined field_35;
    undefined field_36;
    undefined field_37;
    undefined field_38;
    undefined field_39;
    undefined field_40;
    undefined field_41;
    undefined field_42;
    undefined field_43;
    undefined field_44;
    undefined field_45;
    undefined field_46;
    undefined field_47;
    undefined field_48;
    undefined field_49;
    undefined field_50;
    undefined field_51;
    undefined field_52;
    undefined field_53;
    undefined field_54;
    undefined field_55;
} // PlaceHolder Class Structure